# OVH Webhook pour cert-manager DNS challenges
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager-webhook-ovh
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-webhook-ovh
  namespace: cert-manager-webhook-ovh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cert-manager-webhook-ovh
  template:
    metadata:
      labels:
        app: cert-manager-webhook-ovh
    spec:
      containers:
      - name: webhook
        image: baarde/cert-manager-webhook-ovh:latest
        args:
        - --tls-cert-file=/tls/tls.crt
        - --tls-private-key-file=/tls/tls.key
        env:
        - name: GROUP_NAME
          value: acme.bwolf.me
        ports:
        - name: https
          containerPort: 8443
          protocol: TCP
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: https
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: https
        volumeMounts:
        - name: certs
          mountPath: /tls
          readOnly: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: certs
        secret:
          secretName: cert-manager-webhook-ovh-webhook-tls
---
apiVersion: v1
kind: Service
metadata:
  name: cert-manager-webhook-ovh
  namespace: cert-manager-webhook-ovh
spec:
  ports:
  - name: https
    port: 443
    targetPort: https
    protocol: TCP
  selector:
    app: cert-manager-webhook-ovh 