apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: certificates
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/MullerGA/homelab-gitops-temp
    targetRevision: HEAD
    path: infrastructure/certificates
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager-webhook-ovh
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m 