# Installation du webhook OVH officiel via Helm
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-webhook-ovh
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://aureq.github.io/cert-manager-webhook-ovh
    chart: cert-manager-webhook-ovh
    targetRevision: "0.7.4"
    helm:
      values: |
        configVersion: "0.7.4"
        logLevel: 2
        
        # Configuration cert-manager
        certManager:
          namespace: cert-manager
          serviceAccountName: cert-manager-webhook-ovh
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    retry:
      limit: 3
      backoff:
        duration: 5s 