apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/MullerGA/homelab-gitops-temp.git
      revision: HEAD
      directories:
      - path: infrastructure/apps/*
  template:
    metadata:
      name: '{{path.basename}}'
      namespace: argocd
    spec:
      project: homelab
      source:
        repoURL: https://github.com/MullerGA/homelab-gitops-temp.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        # Le namespace est défini dans chaque manifeste YAML
        namespace: infrastructure
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true 