apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/MullerGA/homelab-gitops-temp.git
    path: infrastructure/apps/postgresql
    targetRevision: HEAD
    kustomize:
      buildOptions: "--enable-helm"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: infrastructure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 