apiVersion: v1
kind: ConfigMap
metadata:
  name: pgadmin-config
  namespace: pgadmin
data:
  servers.json: |
    {
      "Servers": {
        "1": {
          "Name": "homelab-postgres",
          "Group": "Applications",
          "Host": "postgres-service.postgresql",
          "Port": 5432,
          "MaintenanceDB": "homelab",
          "Username": "postgres",
          "SSLMode": "prefer"
        }
      }
    } 