apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: infrastructure

resources:
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - secret.yaml
  - ingress.yaml
  - namespace.yaml 