apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: infrastructure
spec:
  type: ClusterIP
  selector:
    app: pgadmin
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http 