apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Le namespace dans lequel toutes les ressources de ce kustomization seront déployées.
# C'est plus propre que de le spécifier dans chaque manifeste.
namespace: infrastructure

# Utilise un chart Helm comme base.
helmCharts:
  - name: postgresql
    repo: https://charts.bitnami.com/bitnami
    version: "14.2.4"
    releaseName: postgresql
    # On spécifie les values directement ici.
    # C'est l'équivalent de ton ancien fichier app.yaml.
    valuesInline:
      primary:
        persistence:
          enabled: true
          storageClass: "longhorn"
          size: 8Gi 