apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  # Attention: changez ce mot de passe !
  POSTGRES_PASSWORD: "supersecretpassword"
  POSTGRES_USER: "postgres"
  POSTGRES_DB: "homelab" 