apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-init
  namespace: infrastructure
data:
  01-create-databases.sql: |
    -- Script d'initialisation PostgreSQL pour Gitea
    -- Idempotent : ne crée que si n'existe pas déjà
    
    -- Créer la base de données si elle n'existe pas
    SELECT 'CREATE DATABASE ${GITEA_DB_NAME:-gitea}'
    WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${GITEA_DB_NAME:-gitea}')\gexec
    
    -- Créer l'utilisateur si il n'existe pas
    DO $$
    BEGIN
        IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = '${GITEA_DB_USER:-gitea}') THEN
            CREATE USER ${GITEA_DB_USER:-gitea} WITH ENCRYPTED PASSWORD '${GITEA_DB_PASSWORD:-G1t3aDbP4ss!2025}';
        END IF;
    END
    $$;
    
    -- Donner les privilèges sur la base
    GRANT ALL PRIVILEGES ON DATABASE ${GITEA_DB_NAME:-gitea} TO ${GITEA_DB_USER:-gitea};
    
  02-configure-gitea-permissions.sql: |
    -- Configuration des permissions schéma public pour Gitea
    -- Ce script s'exécute dans la base gitea
    
    \c ${GITEA_DB_NAME:-gitea}
    
    -- Donner toutes les permissions sur le schéma public
    GRANT ALL PRIVILEGES ON SCHEMA public TO ${GITEA_DB_USER:-gitea};
    GRANT CREATE ON SCHEMA public TO ${GITEA_DB_USER:-gitea};
    
    -- Permissions par défaut pour les futures tables
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${GITEA_DB_USER:-gitea};
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${GITEA_DB_USER:-gitea};
    ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON FUNCTIONS TO ${GITEA_DB_USER:-gitea}; 