apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-init
  namespace: infrastructure
data:
  01-create-databases.sql: |
    -- Base pour Gitea uniquement
    CREATE DATABASE gitea;
    CREATE USER gitea WITH ENCRYPTED PASSWORD 'G1t3aDbP4ss!2025';
    GRANT ALL PRIVILEGES ON DATABASE gitea TO gitea; 