apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data
  namespace: infrastructure
  annotations:
    # Empêcher la suppression accidentelle
    "helm.sh/resource-policy": keep
    "argocd.argoproj.io/sync-options": "Delete=false"
    # Documentation
    "description": "Volume persistant pour base PostgreSQL - NE PAS SUPPRIMER"
  labels:
    app: postgresql
    component: storage
    # Label de protection
    "data.protection": "critical"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi 