apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: infrastructure
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  selector:
    app: postgresql 