apiVersion: v1
kind: ConfigMap
metadata:
  name: gitea-config
data:
  app.ini: |
    [app]
    APP_NAME = Gitea Homelab

    [server]
    ROOT_URL = http://gitea.gmladata.fr/
    SSH_DOMAIN = gitea.gmladata.fr
    HTTP_PORT = 3000
    SSH_PORT = 2222
    DISABLE_SSH = false

    [database]
    DB_TYPE  = postgres
    HOST     = postgres-service.postgresql:5432
    NAME     = gitea
    USER     = gitea
    PASSWD   = anothersecretpassword

    [security]
    INSTALL_LOCK = true
    # Ces clés sont normalement générées par l'installeur. Vous pouvez les remplacer par n'importe quelle longue chaîne aléatoire.
    SECRET_KEY   = fL8qK9wX7zR2jY6mC4bE1sA5pD3oV0uN
    INTERNAL_TOKEN = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE2NjU0MzI0ODN9.Zarela9n73GzL_ysYDEA3eCCgA-M4p2H8LS3z3lALoU 