apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      initContainers:
        - name: setup-gitea
          image: alpine:3.18
          command: ['sh', '-c']
          args:
            - |
              set -e
              if [ ! -f /pvc/config/app.ini ]; then
                echo "Initializing Gitea config..."
                mkdir -p /pvc/config
                cp /config-ro/app.ini /pvc/config/app.ini
              fi
              echo "Initializing Gitea data directories and setting permissions..."
              mkdir -p /pvc/data/log
              chown -R 1000:1000 /pvc
          volumeMounts:
            - name: gitea-storage
              mountPath: /pvc
            - name: gitea-config-map
              mountPath: /config-ro
      containers:
        - name: gitea
          image: docker.gitea.com/gitea:1.23.8-rootless
          ports:
            - containerPort: 3000
              name: web
            - containerPort: 2222
              name: ssh
          env:
            - name: GITEA__database__DB_TYPE
              value: "postgres"
            - name: GITEA__database__HOST
              value: "postgres-service.postgresql:5432"
            - name: GITEA__database__NAME
              value: "gitea"
            - name: GITEA__database__USER
              value: "gitea"
            - name: GITEA__database__PASSWD
              valueFrom:
                secretKeyRef:
                  name: gitea-secret
                  key: GITEA_DATABASE_PASSWORD
          envFrom:
            - secretRef:
                name: gitea-secret
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          volumeMounts:
            - name: gitea-storage
              subPath: data
              mountPath: /data
            - name: gitea-storage
              subPath: config
              mountPath: /etc/gitea
      volumes:
        - name: gitea-storage
          persistentVolumeClaim:
            claimName: gitea-data-pvc
        - name: gitea-config-map
          configMap:
            name: gitea-config 