apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitea-certificate
  namespace: gitea
spec:
  secretName: gitea-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - "gitea.gmladata.fr" 