apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
      - name: gitea
        image: gitea/gitea:1.21-rootless
        ports:
        - containerPort: 3000
          name: http
        - containerPort: 2222
          name: ssh
        env:
        - name: USER_UID
          value: "1000"
        - name: USER_GID
          value: "1000"
        - name: GITEA__database__DB_TYPE
          value: "postgres"
        - name: GITEA__database__HOST
          value: "postgresql.infrastructure.svc.cluster.local:5432"
        - name: GITEA__database__NAME
          valueFrom:
            secretKeyRef:
              name: postgresql-gitea
              key: database
        - name: GITEA__database__USER
          valueFrom:
            secretKeyRef:
              name: postgresql-gitea
              key: username
        - name: GITEA__database__PASSWD
          valueFrom:
            secretKeyRef:
              name: postgresql-gitea
              key: password
        - name: GITEA__server__ROOT_URL
          value: "http://192.168.1.22:30200"
        - name: GITEA__server__HTTP_PORT
          value: "3000"
        - name: GITEA__server__DOMAIN
          value: "192.168.1.22:30200"
        volumeMounts:
        - name: gitea-data
          mountPath: /data
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: gitea-data
        persistentVolumeClaim:
          claimName: gitea-data
 