apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea
  namespace: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      containers:
      - name: gitea
        image: gitea/gitea:1.21-rootless
        ports:
        - containerPort: 3000
          name: http
        - containerPort: 2222
          name: ssh
        env:
        - name: GITEA__database__DB_TYPE
          value: "postgres"
        - name: GITEA__database__HOST
          value: "gitea-db:5432"
        - name: GITEA__database__NAME
          value: "gitea"
        - name: GITEA__database__USER
          value: "gitea"
        - name: GITEA__database__PASSWD
          value: "gitea123"
        - name: GITEA__server__ROOT_URL
          value: "http://192.168.1.22:30200"
        - name: GITEA__server__HTTP_PORT
          value: "3000"
        - name: GITEA__server__DOMAIN
          value: "192.168.1.22:30200"
        volumeMounts:
        - name: gitea-data
          mountPath: /var/lib/gitea
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: gitea-data
        persistentVolumeClaim:
          claimName: gitea-data
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-db
  namespace: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea-db
  template:
    metadata:
      labels:
        app: gitea-db
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "gitea"
        - name: POSTGRES_USER
          value: "gitea"
        - name: POSTGRES_PASSWORD
          value: "gitea123"
        - name: PGDATA
          value: "/var/lib/postgresql/data/pgdata"
        volumeMounts:
        - name: gitea-db-data
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: gitea-db-data
        persistentVolumeClaim:
          claimName: gitea-db-data 