apiVersion: v1
kind: Service
metadata:
  name: gitea
  namespace: gitea
spec:
  type: NodePort
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    nodePort: 30200
  - name: ssh
    port: 2222
    targetPort: 2222
    nodePort: 30222
  selector:
    app: gitea
---
apiVersion: v1
kind: Service
metadata:
  name: gitea-db
  namespace: gitea
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
  selector:
    app: gitea-db 